# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detect.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 900)
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(31, 31, 1031, 771))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.original_img_label = QtWidgets.QLabel(self.layoutWidget)
        self.original_img_label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.original_img_label.sizePolicy().hasHeightForWidth())
        self.original_img_label.setSizePolicy(sizePolicy)
        self.original_img_label.setMinimumSize(QtCore.QSize(94, 24))
        self.original_img_label.setObjectName("original_img_label")
        self.verticalLayout_2.addWidget(self.original_img_label)
        self.predict_result_label = QtWidgets.QLabel(self.layoutWidget)
        self.predict_result_label.setObjectName("predict_result_label")
        self.verticalLayout_2.addWidget(self.predict_result_label)
        self.read_license_plate_label = QtWidgets.QLabel(self.layoutWidget)
        self.read_license_plate_label.setObjectName("read_license_plate_label")
        self.verticalLayout_2.addWidget(self.read_license_plate_label)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.detect_object_text = QtWidgets.QTextBrowser(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.detect_object_text.sizePolicy().hasHeightForWidth())
        self.detect_object_text.setSizePolicy(sizePolicy)
        self.detect_object_text.setObjectName("detect_object_text")
        self.verticalLayout.addWidget(self.detect_object_text)
        self.read_license_plate_text = QtWidgets.QTextBrowser(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.read_license_plate_text.sizePolicy().hasHeightForWidth())
        self.read_license_plate_text.setSizePolicy(sizePolicy)
        self.read_license_plate_text.setObjectName("read_license_plate_text")
        self.verticalLayout.addWidget(self.read_license_plate_text)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.layoutWidget1 = QtWidgets.QWidget(self.splitter)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.select_img_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.select_img_btn.setObjectName("select_img_btn")
        self.horizontalLayout.addWidget(self.select_img_btn)
        self.detect_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.detect_btn.setObjectName("detect_btn")
        self.horizontalLayout.addWidget(self.detect_btn)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.original_img_label.setText(_translate("Form", "原始图片"))
        self.predict_result_label.setText(_translate("Form", "检测结果"))
        self.read_license_plate_label.setText(_translate("Form", "检测车牌"))
        self.select_img_btn.setText(_translate("Form", "原始图片"))
        self.detect_btn.setText(_translate("Form", "检测"))
