# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'choice_fun.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Function(object):
    def setupUi(self, Function):
        Function.setObjectName("Function")
        Function.resize(721, 369)
        self.verticalLayout = QtWidgets.QVBoxLayout(Function)
        self.verticalLayout.setObjectName("verticalLayout")
        self.detect_fun_btn = QtWidgets.QPushButton(Function)
        self.detect_fun_btn.setObjectName("detect_fun_btn")
        self.verticalLayout.addWidget(self.detect_fun_btn)
        self.read_logger_btn = QtWidgets.QPushButton(Function)
        self.read_logger_btn.setObjectName("read_logger_btn")
        self.verticalLayout.addWidget(self.read_logger_btn)
        self.manage_user_btn = QtWidgets.QPushButton(Function)
        self.manage_user_btn.setObjectName("manage_user_btn")
        self.verticalLayout.addWidget(self.manage_user_btn)

        self.retranslateUi(Function)
        QtCore.QMetaObject.connectSlotsByName(Function)

    def retranslateUi(self, Function):
        _translate = QtCore.QCoreApplication.translate
        Function.setWindowTitle(_translate("Function", "Form"))
        self.detect_fun_btn.setText(_translate("Function", "检测功能"))
        self.read_logger_btn.setText(_translate("Function", "日志查看"))
        self.manage_user_btn.setText(_translate("Function", "用户管理"))
