# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manage_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(975, 705)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.user_table = QtWidgets.QTableWidget(Form)
        self.user_table.setObjectName("user_table")
        self.user_table.setColumnCount(0)
        self.user_table.setRowCount(0)
        self.verticalLayout.addWidget(self.user_table)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.username_edit = QtWidgets.QLineEdit(Form)
        self.username_edit.setObjectName("username_edit")
        self.horizontalLayout_2.addWidget(self.username_edit)
        self.password_edit = QtWidgets.QLineEdit(Form)
        self.password_edit.setObjectName("password_edit")
        self.horizontalLayout_2.addWidget(self.password_edit)
        self.is_admin_edit = QtWidgets.QLineEdit(Form)
        self.is_admin_edit.setObjectName("is_admin_edit")
        self.horizontalLayout_2.addWidget(self.is_admin_edit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_btn = QtWidgets.QPushButton(Form)
        self.add_btn.setObjectName("add_btn")
        self.horizontalLayout.addWidget(self.add_btn)
        self.delete_btn = QtWidgets.QPushButton(Form)
        self.delete_btn.setObjectName("delete_btn")
        self.horizontalLayout.addWidget(self.delete_btn)
        self.update_btn = QtWidgets.QPushButton(Form)
        self.update_btn.setObjectName("update_btn")
        self.horizontalLayout.addWidget(self.update_btn)
        self.search_btn = QtWidgets.QPushButton(Form)
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout.addWidget(self.search_btn)
        self.back_btn = QtWidgets.QPushButton(Form)
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout.addWidget(self.back_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.add_btn.setText(_translate("Form", "增"))
        self.delete_btn.setText(_translate("Form", "删"))
        self.update_btn.setText(_translate("Form", "改"))
        self.search_btn.setText(_translate("Form", "查"))
        self.back_btn.setText(_translate("Form", "返回"))
